# Load in NumPy

In [3]:
import numpy as np

# The Basics

In [4]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get dimension
a.ndim

1

In [7]:
# Get shape
b.shape

(2, 3)

In [8]:
# Get type
a.dtype

dtype('int32')

In [9]:
# Get size
a.itemsize

4

In [10]:
# Get total size
a.nbytes

12

# Accessing/Changing Specific Elements

In [11]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
# Get a specific element [r, c]
a[1, -3]

12

In [14]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [16]:
# More fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [19]:
a[1, 5] = 20
print(a)

a[:, 2] = [1, 2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [21]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [22]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [24]:
# Replace
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Arrays

In [25]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [27]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [28]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [29]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.34405494, 0.03337596],
       [0.17783948, 0.01886232],
       [0.33422881, 0.41780235],
       [0.25282415, 0.80692206]])

In [30]:
# Random Integer values
np.random.randint(-4, 8, size=(3, 3))

array([[-3, -2,  6],
       [ 6, -3,  3],
       [ 2,  7,  3]])

In [31]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
output = np.ones((5, 5))

z = np.zeros((3, 3))
z[1, 1] = 9

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Be careful when copying arrays
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100

# Math

In [34]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [35]:
a + 2

array([3, 4, 5, 6])

In [36]:
a - 2

array([-1,  0,  1,  2])

In [37]:
a * 2

array([2, 4, 6, 8])

In [38]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [39]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [40]:
a ** 2

array([ 1,  4,  9, 16])

In [41]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [42]:
a = np.ones((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [43]:
b = np.full((3, 2), 2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [44]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [45]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [46]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.min(stats, axis=1)

array([1, 4])

In [48]:
np.max(stats, axis=0)

array([4, 5, 6])

In [49]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing Arrays

In [50]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [51]:
after = before.reshape((8, 1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [52]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
# Horizontally stacking vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

In [56]:
# Load data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [60]:
# Boolean masking and advanced indexing
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [61]:
# Boolean masking and advanced indexing
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [59]:
# Get index with a list
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])